/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author maria.medeiros
 */
public class telaFinancas extends javax.swing.JFrame {

    /**
     * Creates new form telaFinancas
     */
    public telaFinancas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoValorLeilao = new javax.swing.JTextField();
        labelConsertoEstimado = new javax.swing.JLabel();
        campoConsertoEstimado = new javax.swing.JTextField();
        labelConsertoReal = new javax.swing.JLabel();
        campoConsertoReal = new javax.swing.JTextField();
        labelFipe = new javax.swing.JLabel();
        campoFipe = new javax.swing.JTextField();
        labelValorLeilao = new javax.swing.JLabel();
        okFinancas = new javax.swing.JButton();
        cancelarFinancas = new javax.swing.JButton();
        labelValorVenda = new javax.swing.JLabel();
        campoValorVenda = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelConsertoEstimado.setText("Conserto Estimado");

        campoConsertoEstimado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoConsertoEstimadoActionPerformed(evt);
            }
        });

        labelConsertoReal.setText("Conserto Real");

        labelFipe.setText("FIPE");

        campoFipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoFipeActionPerformed(evt);
            }
        });

        labelValorLeilao.setText("Valor Leilão");

        okFinancas.setText("OK");

        cancelarFinancas.setText("Cancelar");
        cancelarFinancas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarFinancasActionPerformed(evt);
            }
        });

        labelValorVenda.setText("Valor Venda");

        campoValorVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoValorVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelarFinancas)
                        .addGap(18, 18, 18)
                        .addComponent(okFinancas, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelConsertoEstimado)
                            .addComponent(labelConsertoReal)
                            .addComponent(labelFipe)
                            .addComponent(labelValorLeilao)
                            .addComponent(labelValorVenda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(campoConsertoReal, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoConsertoEstimado, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoValorLeilao, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoFipe)
                            .addComponent(campoValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFipe)
                    .addComponent(campoFipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoValorLeilao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelValorLeilao))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelConsertoEstimado)
                    .addComponent(campoConsertoEstimado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoConsertoReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelConsertoReal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelValorVenda))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarFinancas)
                    .addComponent(okFinancas))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoConsertoEstimadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoConsertoEstimadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoConsertoEstimadoActionPerformed

    private void campoFipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoFipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoFipeActionPerformed

    private void cancelarFinancasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarFinancasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarFinancasActionPerformed

    private void campoValorVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoValorVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoValorVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaFinancas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaFinancas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaFinancas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaFinancas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaFinancas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoConsertoEstimado;
    private javax.swing.JTextField campoConsertoReal;
    private javax.swing.JTextField campoFipe;
    private javax.swing.JTextField campoValorLeilao;
    private javax.swing.JTextField campoValorVenda;
    private javax.swing.JButton cancelarFinancas;
    private javax.swing.JLabel labelConsertoEstimado;
    private javax.swing.JLabel labelConsertoReal;
    private javax.swing.JLabel labelFipe;
    private javax.swing.JLabel labelValorLeilao;
    private javax.swing.JLabel labelValorVenda;
    private javax.swing.JButton okFinancas;
    // End of variables declaration//GEN-END:variables
}
